name: whattoeat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  modal_progress_hud: ^0.1.3
  url_launcher: ^5.4.7
  autocomplete_textfield: ^1.7.3




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
